---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: platform
    app.kubernetes.io/version: ${ platform_revision }
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  project: default

  source:
    repoURL: ${ platform_repository }
    path: kustomize/overlays/release
    targetRevision: ${ platform_revision }
    kustomize:
      commonLabels:
        app.kubernetes.io/managed-by: argocd
      patches:
        - target:
          kind: Application
          name: bootstrap
          patch: |
            - op: replace
              path: /spec/source/repoURL
              value: ${ platform_repository }
            - op: replace
              path: /spec/source/targetRevision
              value: ${ platform_revision }
        - target:
          kind: ApplicationSet
          name: sync-platform
          patch: |
            - op: replace
              path: /spec/generators/0/git/repoURL
              value: ${ tenant_repository }
            - op: replace
              path: /spec/generators/0/git/path
              value: clusters/${ cluster_name }

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
